// This file is automatically generated.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// قمت بدمج المتغيرات لضمان عدم وجود تكرار
const SUPABASE_URL = "ضع_رابط_Supabase_الحقيقي_هنا";
const SUPABASE_PUBLISHABLE_KEY = "ضع_مفتاح_Supabase_الحقيقي_هنا";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
